name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: true

    steps:
    - uses: actions/checkout@v3
    - name: Create webassets stub
      run: mkdir -p web/build && touch web/build/index.html
    - name: Format
      run: cargo fmt --check
    - name: Lint
      run: cargo clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
